version: '3.1'
services:
###################################################
  mongo:
    image: mongo:5.0.28
    platform: ${PLATFORM}
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    restart: always
###################################################
  mongoexpress:
    image: mongo-express:1.0.2-18
    platform: ${PLATFORM}
    container_name: mongoexpress
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_BASIC_AUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_BASIC_AUTH_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${DB_NAME}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MONGOEXPRESS_SOCKET}:8081"
    restart: always
    depends_on:
      - mongo
###################################################
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    volumes:
      - qdrant-data:/qdrant/storage
###################################################
  api:
    build:
      context: ../src
    container_name: api
    ports:
      - "${API_SOCKET}:5000"
    restart: always
    depends_on:
      - mongo
      - qdrant
###################################################

volumes:
  mongo-data:
  qdrant-data:
